### PR TITLE
First pass edits

### PR DESCRIPTION
**Pull request by Vachenzo**
I've corrected grammar and html formatting.

### CODE REVIEW

**Comment by tivaliy** [comment]
Thanks

**Comment by Vachenzo** [comment]
np!

**Comment by tivaliy** [comment]
By the way, Vachenzo! Can you check please the result of your pull request http://www.checkio.org/mission/black-holes/ . As you can see ol, li tags don't work (that's why I didn't use it in my case). And сan you check please a new pull request (as native English speaker) from another member https://github.com/tivaliy/checkio-task-black-holes/pull/3/files.

**Comment by Vachenzo** [comment]
I won't have the chance until Monday night or Tuesday but I'll check it out.

**Comment by tivaliy** [comment]
Can you please recheck a new update (some modification were made).
BW, I've removed ol, li tags the didn't work

**Comment by Vachenzo** [comment]
Vitalii, I've made a few fixes to the mission text. Please take a look at
them when you have the chance.

**Pull request merged**
